kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: aliyun
  namespace: default
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aliyun
              image: 'aliyun:security_group'
              env:
                - name: access_key
                  valueFrom:
                    secretKeyRef:
                      name: aliyun
                      key: access_key
                - name: access_secret
                  valueFrom:
                    secretKeyRef:
                      name: aliyun
                      key: access_secret
                - name: region_id
                  value: cn-shanghai
                - name: sg_id
                  value: sg-uf6czvvb79boxtb9dod7
                - name: ip_file
                  value: /data/ip.txt
                - name: port_list
                  value: '22,1521,3306,5432,6379,27017'
              volumeMounts:
                - name: volume-cronjob
                  mountPath: /data
              imagePullPolicy: IfNotPresent
          volumes:
            - name: volume-cronjob
              persistentVolumeClaim:
                claimName: cronjob
          restartPolicy: Never
